apiVersion: v1
kind: Secret

metadata:
  name: amazona-backend-secret

type: Opaque

stringData:

  MONGODB_URL: "mongodb+srv://yousefabozahra26_db_user:jUzaVwJU1xzdDtm@cluster0.qxiu47s.mongodb.net/amazona?appName=Cluster0"

  JWT_SECRET: "amazona-secret"