apiVersion: v1
kind: Secret

metadata:
  name: amazona-backend-secret

type: Opaque

stringData:

  MONGODB_URL: "mongodb+srv://amazona_user:Lc0biPBCHYxDOUjU@cluster0.qxiu47s.mongodb.net/amazona?retryWrites=true&w=majority"


  JWT_SECRET: "amazona-secret"