name: Amazona CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main


jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4


    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20


    - name: Install Backend dependencies
      run: |
        cd backend
        npm install


    - name: Install Frontend dependencies
      run: |
        cd frontend
        npm install


    - name: Build Frontend
      run: |
        cd frontend
        npm run build